-- Auto-generated from data dictionary for table: CompanyPublicFinancialYearlyRelation
-- Columns: 54

DROP TABLE IF EXISTS main.CompanyPublicFinancialYearlyRelation CASCADE;

CREATE TABLE main.CompanyPublicFinancialYearlyRelation (
    "CompanyID" text,  -- Unique identifier for the company (PbID). Relates to unique CompanyID in Company
    "FiscalPeriod" date,  -- End date of the twelve month period for the financial statement
    "FiscalPeriodType" text,  -- Denotes the type of financial statements delivered. Fiscal period type includes 
    "TotalRevenue" float8,  -- Sum of all revenues or sales that the company can attribute to operational activ
    "GrossProfit" float8,  -- Difference between the total revenue and the sum of all direct costs incurred to
    "TotalOperatingProfit_Loss" float8,  -- Profit or loss realized by calculating the difference between sales and total op
    "EarningsBeforeInterestTaxDepreciationAmortization_EBITDA" float8,  -- Represents the earnings the company generated before interest, tax, depreciation
    "EarningsBeforeInterestAndTax_EBIT" float8,  -- Represents the earnings the company generated before paying the interest and tax
    "NetIncomeFromContinuingOperations" float8,  -- Net income or loss of the company before giving effect to after-tax extraordinar
    "NetIncomeAvailableToCommonStockholders" float8,  -- Net income available to common stockholders after accounting for all adjustments
    "NormalizedIncome" float8,  -- Calculation represents earnings adjusted for items that are irregular or unusual
    "DilutedEPSFromContinuingOperations" float8,  -- Earnings per share calculated as a ratio between diluted net income available to
    "NormalizedDilutedEPS" float8,  -- Represents the value of a company''s normalized earnings relative to its diluted
    "DilutedWeightedAverageSharesOutstanding" float8,  -- Weighted average shares outstanding for the accounting period used to calculate 
    "TotalCurrentAssets" float8,  -- Sum of all assets that are expected to be realized in cash, sold or consumed wit
    "NetPropertyPlantAndEquipment" float8,  -- Total net book value of all the tangible assets that are used by a company in it
    "TotalNonCurrentAssets" float8,  -- Sum of all assets that are expected to be realized in cash, sold or consumed aft
    "TotalAssets" float8,  -- Sum of all assets, as recorded in the Balance Sheet
    "TotalCurrentLiabilities" float8,  -- Sum of all liabilities/obligations that are expected to be repaid within one yea
    "TotalNonCurrentLiabilities" float8,  -- Sum of all liabilities/obligations that are expected to be repaid after one year
    "TotalLiabilities" float8,  -- Total value of all liabilities recorded by the company
    "TotalEquity" float8,  -- Before FY2017, the children may not sum up to the parent due to legacy reasons
    "EquityAttributableToParentStockholders" float8,  -- Residual interest in the assets of the enterprise that remains after deducting i
    "TotalDebt" float8,  -- Calculation represents the value of the company''s total borrowing obligations. 
    "WorkingCapital" float8,  -- Calculation represents the difference between the company''s current assets and 
    "CashFlowFromOperatingActivitiesIndirect" float8,  -- Cash generated by or used in operating activities (such as manufacturing and sel
    "CashFlowFromInvestingActivities" float8,  -- Aggregate change in cash position of the company resulting from its long term or
    "CashFlowFromFinancingActivities" float8,  -- Aggregate change in cash position of the company resulting from its financing ac
    "ChangeInCash" float8,  -- Change in cash reported in the cash flow statement
    "CapitalExpenditure_Calc" float8,  -- Represents the calculated variant of Capital Expenditure, which includes all cas
    "IssuanceOf__PaymentsForCommonStockNet" float8,  -- Net increase or decrease in cash due to purchase (treasury) or issuance of commo
    "CashAndCashEquivalentsBeginningOfPeriod" float8,  -- Cash and cash equivalents balance at the beginning of the accounting period, as 
    "CashAndCashEquivalentsEndOfPeriod" float8,  -- Cash and cash equivalents balance at the end of the accounting period, as indica
    "EBITDAMargin" float8,  -- Ratio that represents the value of a company''s EBITDA relative to its total rev
    "RevenuePercentGrowth" float8,  -- Growth rate of the revenue for the period
    "NetIncomeAvailableToCommonStockholdersSequentialPercentGrowth" float8,  -- Sequential growth rate of Net Income Available to Common Stockholders for the pe
    "CurrentRatio" float8,  -- Ratio that represents the value of a company''s current asset relative to its cu
    "QuickRatio" float8,  -- Ratio that represents the value of a company''s most liquid assets relative to i
    "DebtToEquity" float8,  -- Ratio that represents the value of a company''s total debt relative to its total
    "TotalDebtToEquity" float8,  -- Ratio represents the value of the company''s total debt relative to its total eq
    "TotalAssetTurnover" float8,  -- Ratio that represents the value of a company''s revenue generated relative to th
    "NormalizedReturnOnEquity" float8,  -- Ratio that represents the value of a company''s normalized income relative to it
    "NormalizedReturnOnAssets" float8,  -- Ratio that represents the value of a company''s normalized income relative to it
    "NormalizedReturnOnInvestedCapital" float8,  -- Ratio that represents the value of a company''s normalized net operating profit 
    "EnterpriseValue" float8,  -- Calculation represents the entire value of a company. This can be used to measur
    "EnterpriseValueToRevenue" float8,  -- Ratio represents the value of a company''s enterprise value relative to revenue.
    "EnterpriseValueToEBIT" float8,  -- Ratio that represents a company''s enterprise value relative to its EBIT. This c
    "EnterpriseValueToEBITDA" float8,  -- Ratio that represents the value of a company''s enterprise value relative to its
    "Preliminary" text,  -- First-reported values from a preliminary document
    "Original" text,  -- First-reported values from an annual or quarterly document
    "Restated" text,  -- Latest-reported values from a preliminary document
    "Calculated" text,  -- ''Yes'' or ''No'' if values are calculated
    "RowID" text,  -- Unique identifier for the row. This field can be ignored or used at the client''
    "LastUpdated" date  -- Date showing the time any data point in the row was last updated. This column is
);

COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CompanyID" IS 'Unique identifier for the company (PbID). Relates to unique CompanyID in Company';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."FiscalPeriod" IS 'End date of the twelve month period for the financial statement';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."FiscalPeriodType" IS 'Denotes the type of financial statements delivered. Fiscal period type includes ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalRevenue" IS 'Sum of all revenues or sales that the company can attribute to operational activ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."GrossProfit" IS 'Difference between the total revenue and the sum of all direct costs incurred to';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalOperatingProfit_Loss" IS 'Profit or loss realized by calculating the difference between sales and total op';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EarningsBeforeInterestTaxDepreciationAmortization_EBITDA" IS 'Represents the earnings the company generated before interest, tax, depreciation';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EarningsBeforeInterestAndTax_EBIT" IS 'Represents the earnings the company generated before paying the interest and tax';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NetIncomeFromContinuingOperations" IS 'Net income or loss of the company before giving effect to after-tax extraordinar';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NetIncomeAvailableToCommonStockholders" IS 'Net income available to common stockholders after accounting for all adjustments';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NormalizedIncome" IS 'Calculation represents earnings adjusted for items that are irregular or unusual';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."DilutedEPSFromContinuingOperations" IS 'Earnings per share calculated as a ratio between diluted net income available to';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NormalizedDilutedEPS" IS 'Represents the value of a company''s normalized earnings relative to its diluted';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."DilutedWeightedAverageSharesOutstanding" IS 'Weighted average shares outstanding for the accounting period used to calculate ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalCurrentAssets" IS 'Sum of all assets that are expected to be realized in cash, sold or consumed wit';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NetPropertyPlantAndEquipment" IS 'Total net book value of all the tangible assets that are used by a company in it';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalNonCurrentAssets" IS 'Sum of all assets that are expected to be realized in cash, sold or consumed aft';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalAssets" IS 'Sum of all assets, as recorded in the Balance Sheet';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalCurrentLiabilities" IS 'Sum of all liabilities/obligations that are expected to be repaid within one yea';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalNonCurrentLiabilities" IS 'Sum of all liabilities/obligations that are expected to be repaid after one year';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalLiabilities" IS 'Total value of all liabilities recorded by the company';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalEquity" IS 'Before FY2017, the children may not sum up to the parent due to legacy reasons';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EquityAttributableToParentStockholders" IS 'Residual interest in the assets of the enterprise that remains after deducting i';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalDebt" IS 'Calculation represents the value of the company''s total borrowing obligations. ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."WorkingCapital" IS 'Calculation represents the difference between the company''s current assets and ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CashFlowFromOperatingActivitiesIndirect" IS 'Cash generated by or used in operating activities (such as manufacturing and sel';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CashFlowFromInvestingActivities" IS 'Aggregate change in cash position of the company resulting from its long term or';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CashFlowFromFinancingActivities" IS 'Aggregate change in cash position of the company resulting from its financing ac';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."ChangeInCash" IS 'Change in cash reported in the cash flow statement';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CapitalExpenditure_Calc" IS 'Represents the calculated variant of Capital Expenditure, which includes all cas';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."IssuanceOf__PaymentsForCommonStockNet" IS 'Net increase or decrease in cash due to purchase (treasury) or issuance of commo';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CashAndCashEquivalentsBeginningOfPeriod" IS 'Cash and cash equivalents balance at the beginning of the accounting period, as ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CashAndCashEquivalentsEndOfPeriod" IS 'Cash and cash equivalents balance at the end of the accounting period, as indica';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EBITDAMargin" IS 'Ratio that represents the value of a company''s EBITDA relative to its total rev';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."RevenuePercentGrowth" IS 'Growth rate of the revenue for the period';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NetIncomeAvailableToCommonStockholdersSequentialPercentGrowth" IS 'Sequential growth rate of Net Income Available to Common Stockholders for the pe';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."CurrentRatio" IS 'Ratio that represents the value of a company''s current asset relative to its cu';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."QuickRatio" IS 'Ratio that represents the value of a company''s most liquid assets relative to i';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."DebtToEquity" IS 'Ratio that represents the value of a company''s total debt relative to its total';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalDebtToEquity" IS 'Ratio represents the value of the company''s total debt relative to its total eq';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."TotalAssetTurnover" IS 'Ratio that represents the value of a company''s revenue generated relative to th';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NormalizedReturnOnEquity" IS 'Ratio that represents the value of a company''s normalized income relative to it';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NormalizedReturnOnAssets" IS 'Ratio that represents the value of a company''s normalized income relative to it';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."NormalizedReturnOnInvestedCapital" IS 'Ratio that represents the value of a company''s normalized net operating profit ';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EnterpriseValue" IS 'Calculation represents the entire value of a company. This can be used to measur';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EnterpriseValueToRevenue" IS 'Ratio represents the value of a company''s enterprise value relative to revenue.';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EnterpriseValueToEBIT" IS 'Ratio that represents a company''s enterprise value relative to its EBIT. This c';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."EnterpriseValueToEBITDA" IS 'Ratio that represents the value of a company''s enterprise value relative to its';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."Preliminary" IS 'First-reported values from a preliminary document';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."Original" IS 'First-reported values from an annual or quarterly document';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."Restated" IS 'Latest-reported values from a preliminary document';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."Calculated" IS '''Yes'' or ''No'' if values are calculated';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."RowID" IS 'Unique identifier for the row. This field can be ignored or used at the client''';
COMMENT ON COLUMN main.CompanyPublicFinancialYearlyRelation."LastUpdated" IS 'Date showing the time any data point in the row was last updated. This column is';

CREATE INDEX idx_companypublicfinancialyearlyrelation_companyid ON main.CompanyPublicFinancialYearlyRelation ("CompanyID");
CREATE INDEX idx_companypublicfinancialyearlyrelation_rowid ON main.CompanyPublicFinancialYearlyRelation ("RowID");

\COPY main.CompanyPublicFinancialYearlyRelation FROM 'data/CompanyPublicFinancialYearlyRelation.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8', NULL '');
